### ISSUE TITLE
tja2fumen\parsers.py:329: UserWarning: Ignoring unsupported command 'LYRIC'

### ISSUE THREAD

**Issue by Arthurfogo7** [vivaria/tja2fumen#77]
![image](https://github.com/user-attachments/assets/31a713a0-ec9b-46db-8ed1-9976a6d8f4d8)
I don't know why this message is appearing when I try to convert the .tja, what is this command 'LYRIC' that isn't supported?

**Comment by vivaria** [comment]
Sorry for the late reply! 

Many .tja files will include #LYRIC commands (which are only supported by "unofficial simulators", i.e. OpenTaiko, TjaPlayer3, etc.)

But, the official games cannot display lyrics, so TakoTako/tja2fumen discards them, since there is nowhere in the output `.bin` file  for lyric information to go.

Hope this answers your question!
